name: nutrient_flutter
description: A Flutter plugin providing a feature-rich PDF viewing and editing experience to your users with the powerful Nutrient PDF SDK.
version: 5.0.1
homepage: https://nutrient.io/
repository: https://github.com/PSPDFKit/pspdfkit-flutter
issue_tracker: https://support.nutrient.io/hc/en-us/requests/new
documentation: https://nutrient.io/guides/flutter/
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.pspdfkit.flutter.pspdfkit
        pluginClass: PspdfkitPlugin
      ios:
        pluginClass: PspdfkitPlugin
      web:
        pluginClass: NutrientFlutterWeb
        fileName: src/nutrient_flutter_web.dart

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  pigeon: ^24.2.1
  build_runner: ^2.2.1
  pigeon_build_runner: ^1.1.1
  mockito: ^5.3.1

# Ignore false positives for security scanning
false_secrets:
  - example/lib/utils/jwt_util.dart
